import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { locales, type Locale, isValidLocale } from "@/i18n/config";
import { getTranslations } from "@/i18n/get-translations";
import { flattenMessages } from "@/i18n/flatten-messages";
import { IntlProvider } from "@/i18n/IntlProvider";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  // Validate and ensure locale is valid
  const locale = isValidLocale(lang) ? lang : 'en';

  // Load translations for the current locale
  const translations = await getTranslations(locale as Locale);

  // Flatten nested translations for react-intl
  const messages = flattenMessages(translations);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IntlProvider locale={locale as Locale} messages={messages}>
          <LanguageSwitcher />
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}
